[package]
name = "pixelpwnr"
version = "0.1.0"
authors = ["Tim Visée <timvisee@gmail.com>"]

[dependencies]
bufstream = "0.1"
clap = "2.34"
image = "0.23"
num_cpus = "1.13.1"
regex = "1.5"
rayon = "1.5.1"

[profile.release]
lto = true
